version: '3.9'

services:
  # API Doc
  doc:
    image: swaggerapi/swagger-ui:v4.12.0
    container_name: api-document
    ports:
      - "8002:8080"
    volumes:
      - ./doc/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
  # DB
  db:
    build:
      context: ./db
    container_name: db
    environment:
      POSTGRES_DB: "dev"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
  # Web Backend
  app:
    build:
      context: ./demo
    container_name: web_backend
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./demo:/app
    working_dir: /app
    depends_on:
      - db

volumes:
  db_data: